name: go-build-and-publish

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.2

      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure Agent
        run: go run mage.go ConfigureAgent

      - name: Test
        run: mage Test

      - name: Cross Compile
        run: mage XBuildAll

      - name: Publish
        run: mage Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: |
          success() && github.event_name != 'pull_request'
